INSERT INTO `USER` (`USER_ID`, `USERNAME`, `PASSWORD`, `NICKNAME`, `ACTIVATED`)
VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', TRUE);
INSERT INTO `USER` (`USER_ID`, `USERNAME`, `PASSWORD`, `NICKNAME`, `ACTIVATED`)
VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', TRUE);

INSERT INTO `AUTHORITY` (`AUTHORITY_NAME`)
VALUES ('ROLE_USER');
INSERT INTO `AUTHORITY` (`AUTHORITY_NAME`)
VALUES ('ROLE_ADMIN');

INSERT INTO `USER_AUTHORITY` (`USER_ID`, `AUTHORITY_NAME`)
VALUES (1, 'ROLE_USER');
INSERT INTO `USER_AUTHORITY` (`USER_ID`, `AUTHORITY_NAME`)
VALUES (1, 'ROLE_ADMIN');
INSERT INTO `USER_AUTHORITY` (`USER_ID`, `AUTHORITY_NAME`)
VALUES (2, 'ROLE_USER');
